### ISSUE TITLE
多进程模型里 讲到 Chromiu 的渲染器不应该是 Blink 吗？

### ISSUE THREAD

**Issue by xuanhun** [ahangchen/Chromium_doc_zh#1]
多进程模型里 讲到 Chromiu 的渲染器不应该是 Blink 吗？

**Comment by ahangchen** [comment]
这里讲的Blink是刷新器，应该是一个比较小的概念，不是指整个渲染引擎，而且[这个](https://www.chromium.org/developers/design-documents/multi-process-resource-loading)页面应该是需要更新的~
