### ISSUE TITLE
chrome自带的进程管理器进程数和win的进程管理器的chrome进程数不一样

### ISSUE THREAD

**Issue by zurmokeeper** [ahangchen/Chromium_doc_zh#6]
请问为什么Chrome自带的进程管理器进程数和win的进程管理器的chrome进程数不一样？

我的chrome自带的进程管理器进程是9个，然后win的进程管理器的chrome进程数有11个，我一一对比过进程Id了，发现win这边多了两个id，我自己装了5个扩展插件，

但是只有其中的3个在chrome自带的进程管理器里面找到了。没找到的一个叫 Octotree 。当我使用这个插件的时候，chrome那边会显示出来，但是同时win这边也多了一个。所以少的那两个中的一个应该不是 Octotree .

还有一个叫 BuiltWith Technology Profiler 。 但是这个是被我禁用了的。

所以不明白多出来的那两个chrome进程是什么来的？

**Comment by aslistener** [comment]
linux 下面有*zygote* 类型的进程， 表示一个进程壳子。每当需要启动一个render 时，都会在 zygote 进程里面打开内容。 再创建新的 zygote 进程
